### ISSUE TITLE
Parent relative path not getting resolved when mvn install

### ISSUE THREAD

**Issue by arubalac** [Confluex/Zuul#101]
Hi,

I imported the repo into my local and tried to build the package by running the mvn install against the parent pom.xml.

I configured the setting.xml as mentioned in the developer section. I am getting the below exception when tried executing the mvn install . Could you please help in resolving this issue.

Error
=============================
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.confluex:zuul-parent:1.7.1-SNAPSHOT (C:\CISCO\zuul-rep
o\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find com.confluex:base-zuul:po
m:1.2 in https://repo.maven.apache.org/maven2 was cached in the local repository
, resolution will not be reattempted until the update interval of central has el
apsed or updates are forced and 'parent.relativePath' points at no local POM @ l
ine 38, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

Regards
Arun

**Comment by psmith** [comment]
https://github.com/Confluex/base-zuul/blob/master/pom.xml

You would need to checkout https://github.com/Confluex/base-zuul, build and publish it to your local mvn repo.
