### ISSUE TITLE
ZUUL REST API

### ISSUE THREAD

**Issue by panbhatt** [Confluex/Zuul#90]
Hi Team,
  As i went through the source code, i find that most of the times we are replying with ModelAndView. Does there exists an REST API through which I can achieve all the functionality as presented in the UI. 
Please let me know, if something like this exists, as it will be extremely helpful to take the project to next level by creating multiple clients in various languages. 
What i think should be there
1. Get list of env
2. Get list of Keys in Env
3. Set a new key
4. delete key
5. Login of user to Zuul.

**Comment by psmith** [comment]
The rest api isn't fully documented in any way other than through code.  One would have to look in the data and web layers in the zuul project to put everything together.  Also, you can look at the spring client https://github.com/Confluex/zuul-spring-client to see how it is used there.  Also see https://github.com/Confluex/Zuul/wiki/Client-Integration
