### ISSUE TITLE
Encrypt values in Zuul properties files?

### ISSUE THREAD

**Issue by gwalrath** [Confluex/Zuul#91]
Can I encrypt the LDAP bind password value in ldap.properties, or the db password in zuul-data-config.properties? If so, what tool do you recommend?

**Comment by psmith** [comment]
This is the type situation/question, I, and probably most developers have all had.

"Can I encrypt the LDAP bind password value in ldap.properties, or the db password in zuul-data-config.properties?" 
Yes

"If so, what tool do you recommend?"
Whatever encryption tool you want.

Now, getting Zuul to be able to decrypt those, at application start up, with a secure key that doesn't run into the exact same issue as the properties in question, is hard. I want to be wrong on this, and hope someone knows a good way.

 We have to tell Zuul, somehow, what type of encryption is in use, and how to decrypt it, or hard code it.  Which then, how do we encrypt this key? Where do we stop?

Working under the assumption... the goal/question is... How do I keep the passwords, in the properties needed to configure Zuul, secured?

Well, there are a few approaches, and this is a common issue in many apps.  I personally, run the app as a non privileged user, and secure the location that the property files are located with file permissions.  

Additionally, one can remove said property from the properties file, then set a system variable, environment variable, set it in the app server config, or pass it in on the command line... If doing this, I like to set it as an environment variable under the non privileged user, that I run the app under.

These two file are just loaded via spring property place holder, See [old but good, brief blogpost] (http://springtips.blogspot.com/2008/09/configuring-applications-with-spring.html) if you want to make tweaks.
