### ISSUE TITLE
Add an indicator on each property in the UI to indicate if it is encrypted or not

### ISSUE THREAD

**Issue by michael-fei** [Confluex/Zuul#93]
Sometimes it isn't easy to tell if a particular property is encrypted or not (e.g. API key values, certain other random-looking data, etc.). Right now you have to click on the "Edit" drop down menu for each property to see if it is currently encrypted or not. You should consider adding some sort of indicator icon for each property that shows if each one is currently encrypted or not without having to open a drop down menu.

@psmith

**Comment by psmith** [comment]
Yes, it is confusing. I made an issue for this. Tried one fix, fix causes other issues.  It is a surprisingly large change that would need to occur to add it.

https://github.com/Confluex/Zuul/issues/53

**Comment by michael-fei** [comment]
@psmith: I looked at issue #61 and it says it is in milestone 1.6. I'm a little confused, because in the Releases section of the Zuul GitHub site it says that the latest stable release is version 1.5.1, but it also says that the version 1.7.0 is in pre-release. There doesn't seem to be any mention of version 1.6. Is version 1.6 being skipped completely, or am I misunderstanding your versioning scheme?

**Comment by psmith** [comment]
I didn't like the changes in 1.6 so I didn't cut a release.  While it fixed
some things, it caused others and I believe made the encrypted vs non
encrypted issue more confusing for a very different reason.
