### ISSUE TITLE
Unable to see all settings configuration files

### ISSUE THREAD

**Issue by michael-fei** [Confluex/Zuul#95]
When you click on "Settings" in the top navigation bar, the menu list that drops down only shows some of the configuration files you have in your system (I believe there is a maximum number of config files that it will list; ours will only list up to 15). If you have more config files than that, the only way to access them is to type the URL for that config file's setting page directly into the browser address bar (e.g. "https://yourservername/zuul/settings/config-file-not-shown-in-menu").

There should be a way to view a list of all configuration files that you have. I strongly recommend that you fix this UI bug so that either the "Settings" drop down list shows all config files in the system, or create a new UI page that lists all of the config files in the system. This is a pretty big UI bug that limits system usability, so I would suggest the fix for this be given high priority.

@psmith

**Comment by psmith** [comment]
I'll take a look in the morning and see if I can reproduce it.

**Comment by psmith** [comment]
Look at 
https://yourservername/zuul/settings

**Comment by michael-fei** [comment]
Thanks, that page is helpful. However, I think you there should still be a bug in the issue tracker for making that page accessible via the UI. Right now the only way to access that page is to enter the URL directly into the browser. There should be a button or something that brings you to that page.

@psmith
