### ISSUE TITLE
Multiple Servers?

### ISSUE THREAD

**Issue by grwalrath** [Confluex/Zuul#98]
Is it possible to set up Zuul in a HA environment behind a load-balancer, with both servers up at the same time? How would authentication work? I have some idea how to do this in native Tomcat, but Zuul manages its own security.

Does the app support such a setup?

**Comment by psmith** [comment]
Put zuul on X servers, place a load balancer in front of them, point zuul to a db that is setup for HA.  There are too many variables to document all the various ways to do HA.
